name: better_tfi
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  csv: ^6.0.0
  fixnum: ^1.1.1
  protobuf: ^3.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/csv/

flutter_icons:
  android: false               # Disable Android icon generation
  ios: true                    # Enable iOS icon generation
  image_path: "assets/images/better_tfi_logo.png" # Path to your app icon (1024x1024 recommended)
  adaptive_icon_background: "#FFFFFF" # Optional background color for iOS
